import { status } from './status';

export const dummy = [
  { id: 1, taskName: '자소서 쓰기', isComplete: true, status: status.ONGOING },
  { id: 2, taskName: 'Span', isComplete: true, status: status.ONGOING },
  { id: 3, taskName: 'Vagram', isComplete: true, status: status.FINISHED },
  { id: 4, taskName: 'Konklab', isComplete: false, status: status.NOT_STARTED },
  { id: 5, taskName: 'Voyatouch', isComplete: false, status: status.FINISHED },
  {
    id: 6,
    taskName: 'Overhold',
    isComplete: false,
    status: status.NOT_STARTED,
  },
  { id: 7, taskName: 'Regrant', isComplete: false, status: status.NOT_STARTED },
  { id: 8, taskName: 'Tres-Zap', isComplete: true, status: status.NOT_STARTED },
  { id: 9, taskName: 'Tresom', isComplete: false, status: status.FINISHED },
  { id: 10, taskName: 'Zoolab', isComplete: false, status: status.NOT_STARTED },
  // { id: 11, taskName: 'Job', isComplete: false },
  // { id: 12, taskName: 'Konklux', isComplete: false },
  // { id: 13, taskName: 'Duobam', isComplete: false },
  // { id: 14, taskName: 'Keylex', isComplete: false },
  // { id: 15, taskName: 'Bitwolf', isComplete: false },
  // { id: 16, taskName: 'Bigtax', isComplete: false },
  // { id: 17, taskName: 'Tampflex', isComplete: true },
  // { id: 18, taskName: 'Opela', isComplete: true },
  // { id: 19, taskName: 'Hatity', isComplete: false },
  // { id: 20, taskName: 'Zathin', isComplete: false },
  // { id: 21, taskName: 'Otcom', isComplete: false },
  // { id: 22, taskName: 'Opela', isComplete: true },
  // { id: 23, taskName: 'Ventosanzap', isComplete: true },
  // { id: 24, taskName: 'Bytecard', isComplete: false },
  // { id: 25, taskName: 'Alpha', isComplete: true },
  // { id: 26, taskName: 'Tresom', isComplete: true },
  // { id: 27, taskName: 'Cardify', isComplete: true },
  // { id: 28, taskName: 'Tampflex', isComplete: true },
  // { id: 29, taskName: 'Stim', isComplete: true },
  // { id: 30, taskName: 'Tres-Zap', isComplete: false },
  // { id: 31, taskName: 'Opela', isComplete: true },
  // { id: 32, taskName: 'Matsoft', isComplete: true },
  // { id: 33, taskName: 'Rank', isComplete: true },
  // { id: 34, taskName: 'Bitchip', isComplete: false },
  // { id: 35, taskName: 'Cookley', isComplete: true },
  // { id: 36, taskName: 'Sonsing', isComplete: true },
  // { id: 37, taskName: 'It', isComplete: false },
  // { id: 38, taskName: 'Sonsing', isComplete: true },
  // { id: 39, taskName: 'Hatity', isComplete: false },
  // { id: 40, taskName: 'Ronstring', isComplete: true },
  // { id: 41, taskName: 'Namfix', isComplete: false },
  // { id: 42, taskName: 'Matsoft', isComplete: true },
  // { id: 43, taskName: 'Flowdesk', isComplete: false },
  // { id: 44, taskName: 'Overhold', isComplete: true },
  // { id: 45, taskName: 'Keylex', isComplete: false },
  // { id: 46, taskName: 'Cardguard', isComplete: false },
  // { id: 47, taskName: 'Bamity', isComplete: true },
  // { id: 48, taskName: 'Toughjoyfax', isComplete: false },
  // { id: 49, taskName: 'Quo Lux', isComplete: true },
  // { id: 50, taskName: 'Konklab', isComplete: true },
];
